"""users table

Revision ID: 829580f1da82
Revises: 
Create Date: 2019-02-27 11:21:05.431504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '829580f1da82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_index('cpa_alpha2', table_name='connaissancePays')
    op.drop_index('cpa_alpha3', table_name='connaissancePays')
    op.drop_index('cpa_code_unique', table_name='connaissancePays')
    op.drop_table('connaissancePays')
    op.drop_table('descriptionUtilisateur')
    op.drop_table('informationUtilisateur')
    op.drop_table('createurDB')
    op.drop_index('uti_login', table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_table('informationDB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('informationDB',
    sa.Column('idb_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('idb_size', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('idb_ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('utilisateur',
    sa.Column('uti_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uti_login', mysql.CHAR(length=50), nullable=True),
    sa.Column('uti_password', mysql.CHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('uti_ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('uti_login', 'utilisateur', ['uti_login'], unique=True)
    op.create_table('createurDB',
    sa.Column('cdb_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cdb_nom', mysql.CHAR(length=50), nullable=True),
    sa.Column('cdb_prenom', mysql.CHAR(length=50), nullable=True),
    sa.Column('cdb_idb_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cdb_idb_ID'], ['informationDB.idb_ID'], name='createurDB_ibfk_1'),
    sa.PrimaryKeyConstraint('cdb_ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('informationUtilisateur',
    sa.Column('iut_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('iut_nom', mysql.CHAR(length=50), nullable=True),
    sa.Column('iut_prenom', mysql.CHAR(length=50), nullable=True),
    sa.Column('iut_age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('iut_uti_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['iut_uti_ID'], ['utilisateur.uti_ID'], name='informationUtilisateur_ibfk_1'),
    sa.PrimaryKeyConstraint('iut_ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('descriptionUtilisateur',
    sa.Column('dut_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('dut_taille', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('dut_poids', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('dut_couleurCheveux', mysql.CHAR(length=20), nullable=True),
    sa.Column('dut_couleurYeux', mysql.CHAR(length=20), nullable=True),
    sa.Column('dut_uti_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dut_uti_ID'], ['utilisateur.uti_ID'], name='descriptionUtilisateur_ibfk_1'),
    sa.PrimaryKeyConstraint('dut_ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('connaissancePays',
    sa.Column('cpa_ID', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('cpa_code', mysql.INTEGER(display_width=3), autoincrement=False, nullable=False),
    sa.Column('cpa_alpha2', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('cpa_alpha3', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('cpa_nom_en_gb', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('cpa_nom_fr_fr', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('cpa_ID'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_index('cpa_code_unique', 'connaissancePays', ['cpa_code'], unique=True)
    op.create_index('cpa_alpha3', 'connaissancePays', ['cpa_alpha3'], unique=True)
    op.create_index('cpa_alpha2', 'connaissancePays', ['cpa_alpha2'], unique=True)
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
